# @package _global_
defaults:
  - /eval/base
  - _self_
hydra:
  searchpath:
    - file://${oc.env:REPO_ROOT}/config

world:
  env_name: swm/ReacherDMControl-v0
  task: qpos_match

dataset:
  keys_to_cache:
    - action

eval:
  dataset_name: reacher_eval
  callables:
    - method: set_state
      args:
        qpos:
          value: qpos
        qvel:
          value: qvel
    - method: set_target_qpos
      args:
        target_qpos:
          value: goal_qpos
