defaults:
  - /eval/base
  - _self_

hydra:
  searchpath:
    - file://${oc.env:REPO_ROOT}/config

world:
  env_name: swm/TwoRoom-v1
  frame_skip: 1

dataset:
  keys_to_cache:
    - action
    - proprio
    - pos_agent
    - pos_target


eval:
  dataset_name: tworoom_eval




  callables:
    - method: _set_state
      args:
        state:
          value: pos_agent
    - method: _set_goal_state
      args:
        goal_state:
          value: goal_pos_agent
